extend = "../pyproject.toml"

[lint]
ignore = [
    "E501",     # https://github.com/charliermarsh/ruff/issues/3206#issuecomment-1562681390

    "EXE001",   # Shebang is present but file is not executable
    "F821",     # Undefined name
]
