name: npm-update
on:
  schedule:
    - cron: '0 3 * * *'
  # can be run manually on https://github.com/cockpit-project/cockpit/actions
  workflow_dispatch:
jobs:
  npm-update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        run: sudo apt-get install -y npm make

      - name: Set up configuration and secrets
        run: |
          printf '[user]\n\tname = Cockpit Project\n\temail=cockpituous@gmail.com\n' > ~/.gitconfig
          echo '${{ secrets.COCKPITUOUS_TOKEN }}' > ~/.config/github-token

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run npm-update bot
        run: |
          tools/make-bots
          bots/npm-update
