name: po-refresh
on:
  schedule:
    # Run this on Tuesday evening (UTC), so that it's ready for release on
    # Wednesday, with some spare time
    - cron: '0 18 * * 2'
  # can be run manually on https://github.com/cockpit-project/cockpit/actions
  workflow_dispatch:
jobs:
  po-refresh:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    environment: cockpit-weblate
    steps:
      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends npm make gettext pkg-config \
              libpolkit-agent-1-dev libpolkit-gobject-1-dev libsystemd-dev libjson-glib-dev \
              libgnutls28-dev libkrb5-dev libssh-dev libpam0g-dev libpcp3-dev libpcp-import1-dev libpcp-pmda3-dev \
              xsltproc xmlto

      - name: Set up configuration and secrets
        run: |
          mkdir -p ~/.config/cockpit-dev ~/.config/git
          printf '[user]\n\tname = Cockpit Project\n\temail=cockpituous@gmail.com\n' > ~/.config/git/config
          echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/cockpit-dev/github-token

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # need this to also fetch tags
          fetch-depth: 0

      - name: Run po-refresh bot
        run: |
          eval $(ssh-agent)
          ssh-add - <<< '${{ secrets.DEPLOY_KEY }}'

          mkdir -p ~/.config/cockpit-dev
          echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/cockpit-dev/github-token

          tools/make-bots
          bots/po-refresh

          ssh-add -D
          ssh-agent -k
