# truncate the -dist history every Sunday night, to avoid unbounded growth
name: prune-dist
on:
  schedule:
    - cron: '0 1 * * 0'
  # can be run manually on https://github.com/cockpit-project/cockpit/actions
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      HEAD_SHA: ${{ github.sha }}
      DIST_REPO: https://github.com/${{ github.repository }}-dist.git
    steps:
      - name: Set up configuration and secrets
        run: |
          printf '[user]\n\tname = Cockpit Project\n\temail=cockpituous@gmail.com\n' > ~/.gitconfig
          # we push to -dist repo via https://github.com, that needs our cockpituous token
          git config --global credential.helper store
          echo 'https://token:${{ secrets.COCKPITUOUS_TOKEN }}@github.com' >> ~/.git-credentials

      - name: Clone -dist repo
        run: |
          git clone "${DIST_REPO}" dist-repo

      - name: Delete old tags
        run: |
          set -ex

          cd dist-repo
          now="$(date +%s)"
          for tag in $(git tag -l); do
              tag_time="$(git show -s --format=%at $tag)"
              if [ "$tag" = "sha-${HEAD_SHA}" ]; then
                  echo "$tag refers to current project default branch HEAD, keeping"
              elif [ $((now - tag_time)) -ge 604800 ]; then
                  echo "$tag is older than 7 days, deleting..."
                  git push origin ":$tag"
              else
                  echo "$tag is younger than 7 days, keeping"
              fi
          done
